import os

SPOTIFY_CLIENT_ID = os.environ.get('SPOTIFY_CLIENT_ID')
SPOTIFY_CLIENT_TOKEN = os.environ.get('SPOTIFY_CLIENT_TOKEN')
SPOTIFY_REDIRECT_URL = os.environ.get('SPOTIFY_REDIRECT_URL')
SPOTIFY_API_HOST_URL = os.environ.get('SPOTIFY_API_HOST_URL')

print("CONFIG: ", SPOTIFY_CLIENT_ID)